import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'id' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, variables?: Record<string, string | number>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  id: {
    // General / Header / Footer
    'Pancaran Lelang': 'Pancaran Lelang',
    'Katalog Eksternal': 'Katalog Eksternal',
    'Katalog Eksternal (Public)': 'Katalog Eksternal (Publik)',
    'Area Admin Internal': 'Area Admin Internal',
    'Login Admin': 'Login Admin',
    'Logout Admin': 'Keluar Admin',
    'Admin Active': 'Admin Aktif',
    'Keluar': 'Keluar',
    'Pilih Tampilan': 'Pilih Tampilan',
    'Menu Admin': 'Menu Admin',
    'Dashboard Ringkasan': 'Dashboard Ringkasan',
    'Kelola Aset (Tambah & Bids)': 'Kelola Aset (Tambah & Bids)',
    'Manajemen Akses': 'Manajemen Akses',
    'Status Koneksi': 'Status Koneksi',
    'Lelang Aktif': 'Lelang Aktif',
    'Sedang Berjalan': 'Sedang Berjalan',
    'Unit Terjual': 'Unit Terjual',
    'Otorisasi Diperlukan': 'Otorisasi Diperlukan',
    'Halaman internal manajemen Pancaran Lelang dilindungi enkripsi. Silakan masuk menggunakan akun kredensial Anda.': 'Halaman internal manajemen Pancaran Lelang dilindungi enkripsi. Silakan masuk menggunakan akun kredensial Anda.',
    'Masuk Sekarang': 'Masuk Sekarang',
    'Hak Cipta Dilindungi': 'Hak Cipta Dilindungi',
    'Pool Marunda': 'Pool Marunda',
    'Pool Cakung': 'Pool Cakung',
    'Pool Teluk Gong': 'Pool Teluk Gong',
    'Cilincing': 'Cilincing',
    'Admin Digital Solution': 'Admin Digital Solution',
    'AKUN MASUK:': 'AKUN MASUK:',
    'COMPANY INFO': 'INFORMASI PERUSAHAAN',
    'Our Office': 'Kantor Kami',
    'Head Office 1 :': 'Kantor Pusat 1 :',
    'HUBUNGI KAMI': 'HUBUNGI KAMI',
    'Lokasi Pool Inspeksi:': 'Lokasi Pool Inspeksi:',
    'Portal resmi likuidasi armada aktif dan alat berat dari ekosistem operasional Pancaran Group. Transparan, tepercaya, dan terintegrasi.': 'Portal resmi likuidasi armada aktif dan alat berat dari ekosistem operasional Pancaran Group. Transparan, tepercaya, dan terintegrasi.',
    'Syarat & Ketentuan': 'Syarat & Ketentuan',
    'Kebijakan Privasi': 'Kebijakan Privasi',

    // Catalog View & Cards
    'Cari aset lelang...': 'Cari aset lelang...',
    'Merek': 'Merek',
    'Kategori': 'Kategori',
    'Kondisi': 'Kondisi',
    'Lokasi': 'Lokasi',
    'Semua Merek': 'Semua Merek',
    'Semua Kategori': 'Semua Kategori',
    'Semua Kondisi': 'Semua Kondisi',
    'Semua Lokasi': 'Semua Lokasi',
    'Menampilkan {count} aset yang memenuhi kriteria': 'Menampilkan {count} aset yang memenuhi kriteria',
    'Terbuka': 'Terbuka',
    'Terjual': 'Terjual',
    'Th': 'Th',
    'Plat': 'Plat',
    'Harga Awal': 'Harga Awal',
    'Harga Pembuka': 'Harga Pembuka',
    'Penawaran Tertinggi': 'Penawaran Tertinggi',
    'Belum ada penawaran': 'Belum ada penawaran',
    'Penawaran': 'Penawaran',
    'Penawaran Masuk': 'Penawaran Masuk',
    'Tawar Aset': 'Tawar Aset',
    'Brand:': 'Brand:',
    'Kategori:': 'Kategori:',
    'Tahun:': 'Tahun:',
    'No. Polisi:': 'No. Polisi:',
    'Kondisi:': 'Kondisi:',
    'Lokasi:': 'Lokasi:',
    'Lihat Detail': 'Lihat Detail',
    'Lihat Detail & Ajukan Bid': 'Lihat Detail & Ajukan Bid',
    'Detail Unit Lelang': 'Detail Unit Lelang',
    'Kembali ke Katalog': 'Kembali ke Katalog',
    'Spesifikasi Unit': 'Spesifikasi Unit',
    'Tahun Pembuatan': 'Tahun Pembuatan',
    'Nomor Polisi': 'Nomor Polisi',
    'Kondisi Fisik': 'Kondisi Fisik',
    'Deskripsi Tambahan': 'Deskripsi Tambahan',
    'Informasi & Tata Cara Lelang': 'Informasi & Tata Cara Lelang',
    'Aset ini bersifat tangan pertama, memiliki dokumen legalitas (STNK, BPKB, KIR) lengkap dan siap dipindahtangankan setelah pelunasan.': 'Aset ini bersifat tangan pertama, memiliki dokumen legalitas (STNK, BPKB, KIR) lengkap dan siap dipindahtangankan setelah pelunasan.',
    'Penawaran dilakukan secara terbuka. Setiap penawaran baru wajib lebih tinggi dari penawaran saat ini.': 'Penawaran dilakukan secara terbuka. Setiap penawaran baru wajib lebih tinggi dari penawaran saat ini.',
    'Setelah mengajukan penawaran, tim logistik kami akan menghubungi Anda untuk verifikasi dokumen dan penjadwalan inspeksi unit di lokasi pool terkait.': 'Setelah mengajukan penawaran, tim logistik kami akan menghubungi Anda untuk verifikasi dokumen dan penjadwalan inspeksi unit di lokasi pool terkait.',
    'Riwayat Penawaran Saat Ini': 'Riwayat Penawaran Saat Ini',
    'Nama': 'Nama',
    'Nilai Bid': 'Nilai Bid',
    'Waktu': 'Waktu',
    'Belum ada penawaran masuk untuk unit ini. Jadilah penawar pertama!': 'Belum ada penawaran masuk untuk unit ini. Jadilah penawar pertama!',
    'Formulir Pengajuan Bid Resmi': 'Formulir Pengajuan Bid Resmi',
    'Masukkan nama lengkap Anda...': 'Masukkan nama lengkap Anda...',
    'Contoh: 08123456789': 'Contoh: 08123456789',
    'Masukkan alamat email aktif...': 'Masukkan alamat email aktif...',
    'Rencana Tanggal Survey': 'Rencana Tanggal Survey',
    'Rencana Jam Survey': 'Rencana Jam Survey',
    'Harga Penawaran Anda (Rupiah)': 'Harga Penawaran Anda (Rupiah)',
    'Min. Penawaran Berikutnya:': 'Min. Penawaran Berikutnya:',
    'Kirim Penawaran & Jadwalkan Survey': 'Kirim Penawaran & Jadwalkan Survey',
    'Memproses...': 'Memproses...',
    'Silakan isi semua data dengan benar.': 'Silakan isi semua data dengan benar.',
    'Penawaran Anda harus lebih besar dari penawaran tertinggi saat ini!': 'Penawaran Anda harus lebih besar dari penawaran tertinggi saat ini!',
    'Penawaran Anda Berhasil Dikirim!': 'Penawaran Anda Berhasil Dikirim!',
    'Terima kasih telah mengajukan penawaran. Tim Pancaran Logistic akan segera menghubungi Anda di nomor kontak yang tertera.': 'Terima kasih telah mengajukan penawaran. Tim Pancaran Logistic akan segera menghubungi Anda di nomor kontak yang tertera.',
    'Tutup': 'Tutup',
    'Pemenang Lelang': 'Pemenang Lelang',
    'Pemenang': 'Pemenang',
    'Penawaran Pemenang': 'Penawaran Pemenang',
    'Kontak Pemenang': 'Kontak Pemenang',
    'Belum ada penawar': 'Belum ada penawar',
    'Perkecil': 'Perkecil',
    'Perbesar / Fokus Detail': 'Perbesar / Fokus Detail',
    'Seret/Scroll untuk melihat bagian gambar • Klik gambar untuk mengecilkan': 'Seret/Scroll untuk melihat bagian gambar • Klik gambar untuk mengecilkan',
    'Klik gambar atau tombol untuk memperbesar penuh & jelas': 'Klik gambar atau tombol untuk memperbesar penuh & jelas',
    'Sudah Dibooking': 'Sudah Dibooking',
    'Pilih Tanggal Kunjungan': 'Pilih Tanggal Kunjungan',
    'Pilih Sesi Jam Kunjungan': 'Pilih Sesi Jam Kunjungan',
    'Ready': 'Tersedia',
    'Selected': 'Dipilih',
    'Booked': 'Penuh',
    'Sesi Pagi I': 'Sesi Pagi I',
    'Sesi Pagi II': 'Sesi Pagi II',
    'Sesi Siang I': 'Sesi Siang I',
    'Sesi Sore II': 'Sesi Sore II',
    'Informasi Lokasi & Pendampingan': 'Informasi Lokasi & Pendampingan',
    'Jadwal survei pada tanggal dan jam tersebut sudah di-booking oleh calon pembeli lain. Mohon pilih waktu atau hari lain.': 'Jadwal survei pada tanggal dan jam tersebut sudah di-booking oleh calon pembeli lain. Mohon pilih waktu atau hari lain.',
    'Klik gambar untuk berikutnya • Klik di luar untuk kembali': 'Klik gambar untuk berikutnya • Klik di luar untuk kembali',
    'Klik gambar atau di luar untuk kembali': 'Klik gambar atau di luar untuk kembali',
    'Klik gambar untuk memperkecil • Geser untuk menjelajah detail': 'Klik gambar untuk memperkecil • Geser untuk menjelajah detail',
    'Klik gambar untuk memperbesar • Klik di luar untuk kembali': 'Klik gambar untuk memperbesar • Klik di luar untuk kembali',
    'Zoom In': 'Zoom In',
    'Zoom Out': 'Zoom Out',

    // Login Modal
    'Otoritas Internal Admin': 'Otoritas Internal Admin',
    'Gunakan email & password terdaftar untuk mengelola sistem lelang.': 'Gunakan email & password terdaftar untuk mengelola sistem lelang.',
    'Email atau password salah. Pastikan kredensial benar.': 'Email atau password salah. Pastikan kredensial benar.',
    'ALAMAT EMAIL KERJA': 'ALAMAT EMAIL KERJA',
    'KATA SANDI (PASSWORD)': 'KATA SANDI (PASSWORD)',
    'Masuk Aplikasi': 'Masuk Aplikasi',
    'Petunjuk Akun Penguji:': 'Petunjuk Akun Penguji:',
    'Untuk menguji fitur admin, silakan klik tombol di bawah untuk mengisi kredensial default dari user secara instan.': 'Untuk menguji fitur admin, silakan klik tombol di bawah untuk mengisi kredensial default dari user secara instan.',
    'Isi Kredensial Penguji': 'Isi Kredensial Penguji',

    // Admin Dashboard
    'Dashboard Utama & Analitik': 'Dashboard Utama & Analitik',
    'Ringkasan metrik performa sistem lelang Pancaran Logistics secara real-time.': 'Ringkasan metrik performa sistem lelang Pancaran Logistics secara real-time.',
    'Total Asset': 'Total Aset',
    'Unit di Database': 'Unit di Database',
    'Sedang Aktif': 'Sedang Aktif',
    'Menerima Penawaran': 'Menerima Penawaran',
    'Aset Terjual': 'Aset Terjual',
    'Sudah Diproses': 'Sudah Diproses',
    'Total Bidder': 'Total Penawar',
    'Telah Berpartisipasi': 'Telah Berpartisipasi',
    'Aset Terpopuler': 'Aset Terpopuler',
    'Dengan Penawaran Terbanyak': 'Dengan Penawaran Terbanyak',
    'Daftar Aktivitas Bid Terbaru': 'Daftar Aktivitas Bid Terbaru',
    'Aktivitas Terbaru': 'Aktivitas Terbaru',
    'Daftar pengajuan penawaran harga dari calon pembeli eksternal.': 'Daftar pengajuan penawaran harga dari calon pembeli eksternal.',
    'Semua Riwayat': 'Semua Riwayat',
    'Aset': 'Aset',
    'Penawar': 'Penawar',
    'Jumlah Penawaran': 'Jumlah Penawaran',
    'Tanggal & Waktu': 'Tanggal & Waktu',
    'Status': 'Status',
    'Tindakan': 'Tindakan',
    'Belum ada aktivitas penawaran yang terdaftar di sistem.': 'Belum ada aktivitas penawaran yang terdaftar di sistem.',
    'Lihat Detail Aset': 'Lihat Detail Aset',

    // Admin Assets
    'Daftar Manajemen Aset': 'Daftar Manajemen Aset',
    'Kelola unit logistik yang dilelang, tambahkan unit baru, dan pantau histori penawaran masuk.': 'Kelola unit logistik yang dilelang, tambahkan unit baru, dan pantau histori penawaran masuk.',
    'Tambah Unit Baru': 'Tambah Unit Baru',
    'Daftarkan Aset Lelang Baru': 'Daftarkan Aset Lelang Baru',
    'Lengkapi spesifikasi teknis dan detail dokumen kendaraan di bawah.': 'Lengkapi spesifikasi teknis dan detail dokumen kendaraan di bawah.',
    'Ubah Detail Unit': 'Ubah Detail Unit',
    'Perbarui spesifikasi teknis dan kelengkapan dokumen kendaraan lelang.': 'Perbarui spesifikasi teknis dan kelengkapan dokumen kendaraan lelang.',
    'Semua Aset': 'Semua Aset',
    'Aktif / Open': 'Aktif / Open',
    'Terjual / Sold': 'Terjual / Sold',
    'Cari aset...': 'Cari aset...',
    'Tipe': 'Tipe',
    'Aksi': 'Aksi',
    'Belum ada aset lelang yang cocok dengan pencarian Anda.': 'Belum ada aset lelang yang cocok dengan pencarian Anda.',
    'PILIH TEMPLATE KENDARAAN (OPSIONAL)': 'PILIH TEMPLATE KENDARAAN (OPSIONAL)',
    'Memilih template akan otomatis mengisi Nama, Brand, Kategori, dan gambar ilustrasi standar.': 'Memilih template akan otomatis mengisi Nama, Brand, Kategori, dan gambar ilustrasi standar.',
    'FORMULIR MANAJEMEN UNIT ASET': 'FORMULIR MANAJEMEN UNIT ASET',
    'Nama Kendaraan / Aset': 'Nama Kendaraan / Aset',
    'Merek / Brand': 'Merek / Brand',
    'Kategori Kendaraan': 'Kategori Kendaraan',
    'Tahun': 'Tahun',
    'Nomor Registrasi (Plat)': 'Nomor Registrasi (Plat)',
    'Sangat Baik': 'Sangat Baik',
    'Baik': 'Baik',
    'Cukup': 'Cukup',
    'Butuh Perbaikan': 'Butuh Perbaikan',
    'Lokasi Pool': 'Lokasi Pool',
    'Harga Awal (IDR)': 'Harga Awal (IDR)',
    'Deskripsi & Spesifikasi Tambahan': 'Deskripsi & Spesifikasi Tambahan',
    'Batal': 'Batal',
    'Simpan Perubahan': 'Simpan Perubahan',
    'Tambah Unit ke Sistem': 'Tambah Unit ke Sistem',
    'Unggah Foto Unit': 'Unggah Foto Unit',
    'Klik untuk unggah atau seret foto ke sini': 'Klik untuk unggah atau seret foto ke sini',
    'Format JPG, PNG maks 5MB. Gambar akan otomatis dikompresi untuk performa optimal.': 'Format JPG, PNG maks 5MB. Gambar akan otomatis dikompresi untuk performa optimal.',
    'Foto berhasil diunggah': 'Foto berhasil diunggah',
    'Hapus Foto': 'Hapus Foto',
    'Gambar Utama': 'Gambar Utama',
    'PILIH ALAT BANTU': 'PILIH ALAT BANTU',
    'Dapatkan Saran Deskripsi dengan AI': 'Dapatkan Saran Deskripsi dengan AI',
    'Saran Deskripsi': 'Saran Deskripsi',
    'Gunakan Saran AI': 'Gunakan Saran AI',
    'Silakan pilih template atau isi Brand & Kategori terlebih dahulu agar AI dapat menganalisis deskripsi yang relevan.': 'Silakan pilih template atau isi Brand & Kategori terlebih dahulu agar AI dapat menganalisis deskripsi yang relevan.',
    'Detail Histori Penawaran': 'Detail Histori Penawaran',
    'Pilih aset di sebelah kiri untuk melihat detail spesifikasi dan histori penawaran secara menyeluruh.': 'Pilih aset di sebelah kiri untuk melihat detail spesifikasi dan histori penawaran secara menyeluruh.',
    'Detail Spesifikasi': 'Detail Spesifikasi',
    'Histori Bid': 'Histori Bid',
    'Ubah Atribut': 'Ubah Atribut',
    'Ubah Status': 'Ubah Status',
    'Buka Penawaran': 'Buka Penawaran',
    'Tutup / Selesaikan (Sold)': 'Tutup / Selesaikan (Sold)',
    'Hapus Unit': 'Hapus Unit',
    'Apakah Anda yakin ingin menghapus aset ini secara permanen dari sistem database?': 'Apakah Anda yakin ingin menghapus aset ini secara permanen dari sistem database?',
    'Ya, Hapus': 'Ya, Hapus',
    'Tidak': 'Tidak',
    'Rencana Survey:': 'Rencana Survey:',
    'Belum ada penawaran untuk unit ini.': 'Belum ada penawaran untuk unit ini.',
    'Bids Masuk': 'Bids Masuk',
    'Hubungi': 'Hubungi',

    // Additional Admin Assets Dialogs & Details
    'PLAT NOMOR': 'PLAT NOMOR',
    'TAHUN PRODUKSI': 'TAHUN PRODUKSI',
    'KONDISI FISIK': 'KONDISI FISIK',
    'LOKASI SEEDING': 'LOKASI SEEDING',
    'DESKRIPSI INTERNAL': 'DESKRIPSI INTERNAL',
    'Histori Penawaran': 'Histori Penawaran',
    'Bids Tertinggi Pertama': 'Bids Tertinggi Pertama',
    'Jadwal Survei': 'Jadwal Survei',
    'Belum ada penawaran harga masuk untuk aset ini.': 'Belum ada penawaran harga masuk untuk aset ini.',
    'Konfirmasi Hapus Unit': 'Konfirmasi Hapus Unit',
    'Edit Unit Aset': 'Edit Unit Aset',
    'Hapus Unit Aset': 'Hapus Unit Aset',
    'Tutup Detail': 'Tutup Detail',
    'Status Lelang Saat Ini:': 'Status Lelang Saat Ini:',
    'Menerima Bid': 'Menerima Bid',
    'Buka Bid': 'Buka Bid',
    'Set Terjual': 'Set Terjual',
    'Sebelumnya': 'Sebelumnya',
    'Berikutnya': 'Berikutnya',
    'Tambah': 'Tambah',
    'Ketik atau tempel tautan gambar, lalu tekan tombol "Tambah" atau Enter untuk memasukkan ke galeri unit lelang ini.': 'Ketik atau tempel tautan gambar, lalu tekan tombol "Tambah" atau Enter untuk memasukkan ke galeri unit lelang ini.',
    'Simpan Unit Baru': 'Simpan Unit Baru',
    'Kelola Aset Lelang': 'Kelola Aset Lelang',
    'Daftarkan armada logistik baru, pantau status lelang, dan verifikasi riwayat penawaran.': 'Daftarkan armada logistik baru, pantau status lelang, dan verifikasi riwayat penawaran.',
    'Tambah Aset Baru': 'Tambah Aset Baru',
    'Cari berdasarkan nama aset, plat, kategori...': 'Cari berdasarkan nama aset, plat, kategori...',
    'Semua Brand': 'Semua Brand',
    'Tidak ada aset lelang yang cocok dengan kriteria pencarian.': 'Tidak ada aset lelang yang cocok dengan kriteria pencarian.',
    'Reset Semua Filter': 'Reset Semua Filter',
    'Merek (Brand) *': 'Merek (Brand) *',
    'Kategori Unit *': 'Kategori Unit *',
    'Tahun Produksi *': 'Tahun Produksi *',
    'No. Registrasi / Plat Nomor': 'No. Registrasi / Plat Nomor',
    'Kondisi Fisik Unit *': 'Kondisi Fisik Unit *',
    'Harga Awal Lelang (IDR) *': 'Harga Awal Lelang (IDR) *',
    'Lokasi Pool / Depo Unit *': 'Lokasi Pool / Depo Unit *',
    'Foto / Gambar Unit * (Bisa Unggah Banyak)': 'Foto / Gambar Unit * (Bisa Unggah Banyak)',
    'Pilih atau Seret Foto-Foto Armada': 'Pilih atau Seret Foto-Foto Armada',
    'Mendukung format PNG, JPG, JPEG (Bisa pilih banyak sekaligus, Max 5MB per file)': 'Mendukung format PNG, JPG, JPEG (Bisa pilih banyak sekaligus, Max 5MB per file)',
    'Koleksi Foto Terunggah ({count})': 'Koleksi Foto Terunggah ({count})',
    'Cover Utama': 'Cover Utama',
    'Tambah Foto via Tautan Gambar (URL)': 'Tambah Foto via Tautan Gambar (URL)',
    'Apakah Anda yakin ingin menghapus {name} secara permanen? Data historis penawaran juga akan ikut terhapus.': 'Apakah Anda yakin ingin menghapus {name} secara permanen? Data historis penawaran juga akan ikut terhapus.',

    // Admin Users
    'Kelola Hak Akses Admin': 'Kelola Hak Akses Admin',
    'Tambahkan, hapus, dan atur peran pengguna internal yang dapat masuk ke dashboard administrasi.': 'Tambahkan, hapus, dan atur peran pengguna internal yang dapat masuk ke dashboard administrasi.',
    'Daftarkan Admin Baru': 'Daftarkan Admin Baru',
    'Nama Lengkap': 'Nama Lengkap',
    'Alamat Email Pancaran': 'Alamat Email Pancaran',
    'Peran / Hak Akses': 'Peran / Hak Akses',
    'Super Admin': 'Super Admin',
    'Admin Operasional': 'Admin Operasional',
    'Admin Keuangan': 'Admin Keuangan',
    'Daftarkan': 'Daftarkan',
    'Akun Terdaftar': 'Akun Terdaftar',
    'Peran': 'Peran',
    'Bergabung': 'Bergabung',
    'Anda': 'Anda',
    'Hapus Akses': 'Hapus Akses',
    'Apakah Anda yakin ingin menghapus hak akses untuk admin ini?': 'Apakah Anda yakin ingin menghapus hak akses untuk admin ini?',

    // Additional Admin Users Keys
    'Manajemen Akses Admin': 'Manajemen Akses Admin',
    'Buat akses administrator baru, tinjau tingkatan hak akses, dan kelola otoritas keamanan internal Pancaran Lelang.': 'Buat akses administrator baru, tinjau tingkatan hak akses, dan kelola otoritas keamanan internal Pancaran Lelang.',
    'Buat Akses Baru': 'Buat Akses Baru',
    'Daftarkan akun email karyawan baru untuk memberikan akses masuk ke dashboard internal.': 'Daftarkan akun email karyawan baru untuk memberikan akses masuk ke dashboard internal.',
    'Nama Lengkap Admin': 'Nama Lengkap Admin',
    'Contoh: Achmad Subagja': 'Contoh: Achmad Subagja',
    'Harus berupa email institusi Pancaran.': 'Harus berupa email institusi Pancaran.',
    'Tingkatan Peran (Role)': 'Tingkatan Peran (Role)',
    'Admin Operasional (Input & Kelola Aset)': 'Admin Operasional (Input & Kelola Aset)',
    'Admin Keuangan (Otorisasi Unit Terjual)': 'Admin Keuangan (Otorisasi Unit Terjual)',
    'Super Admin (Akses Penuh)': 'Super Admin (Akses Penuh)',
    'Buat Hak Akses': 'Buat Hak Akses',
    'Daftar Administrator Terdaftar': 'Daftar Administrator Terdaftar',
    'Daftar staf internal Pancaran Logistics yang memegang otoritas sistem Lelang.': 'Daftar staf internal Pancaran Logistics yang memegang otoritas sistem Lelang.',
    'Nama / Karyawan': 'Nama / Karyawan',
    'Email Akun': 'Email Akun',
    'Terdaftar Pada': 'Terdaftar Pada',
    'Ya': 'Ya',
    'Mohon lengkapi nama dan email admin.': 'Mohon lengkapi nama dan email admin.',
    'Email admin tersebut sudah terdaftar.': 'Email admin tersebut sudah terdaftar.',
    'Format email tidak valid. Direkomendasikan menggunakan email institusi Pancaran.': 'Format email tidak valid. Direkomendasikan menggunakan email institusi Pancaran.',
    'Akses admin berhasil dibuat untuk': 'Akses admin berhasil dibuat untuk',
    'Anda sedang masuk dengan akun ini': 'Anda sedang masuk dengan akun ini',
    'Akun Super Admin Utama tidak bisa dihapus': 'Akun Super Admin Utama tidak bisa dihapus',

    // New keys for Admin Dashboard and other pages
    'Dashboard Pancaran Lelang': 'Dashboard Pancaran Lelang',
    'Halo Admin, kelola aset lelang komersial, pantau penawaran harga, dan atur survei fisik dalam satu portal terpadu.': 'Halo Admin, kelola aset lelang komersial, pantau penawaran harga, dan atur survei fisik dalam satu portal terpadu.',
    'Waktu Sistem (WIB)': 'Waktu Sistem (WIB)',
    'Sukses Lelang': 'Sukses Lelang',
    'Aset Aktif': 'Aset Aktif',
    'Partisipan Unik': 'Partisipan Unik',
    'Total Aset per Brand': 'Total Aset per Brand',
    'Porsi distribusi armada lelang Pancaran Logistics berdasarkan merek manufaktur.': 'Porsi distribusi armada lelang Pancaran Logistics berdasarkan merek manufaktur.',
    'Unit': 'Unit',
    'Belum ada data armada/brand tersedia.': 'Belum ada data armada/brand tersedia.',
    'Per 2026. Semua aset fisik di pool internal.': 'Per 2026. Semua aset fisik di pool internal.',
    'Jadwal Survei Fisik': 'Jadwal Survei Fisik',
    'Daftar booking kunjungan calon pembeli untuk inspeksi fisik kendaraan.': 'Daftar booking kunjungan calon pembeli untuk inspeksi fisik kendaraan.',
    'Semua': 'Semua',
    'Mendatang': 'Mendatang',
    'Riwayat': 'Riwayat',
    'Cari nama bidder, brand, atau armada...': 'Cari nama bidder, brand, atau armada...',
    'Selesai': 'Selesai',
    'Bidder': 'Bidder',
    'Lihat Aset': 'Lihat Aset',
    'Tidak ada jadwal survei fisik ditemukan.': 'Tidak ada jadwal survei fisik ditemukan.',

    // Public Catalog & Banner Keys
    'Portal Penawaran Umum (External)': 'Portal Penawaran Umum (Eksternal)',
    'Likuidasi Armada Logistik & Heavy Equipment': 'Likuidasi Armada Logistik & Heavy Equipment',
    'Dapatkan truk tangki, wingbox, trailer, cargo van, dan alat berat kualitas terbaik langsung dari ekosistem operasional Pancaran Logistics. Transparan, terpercaya, dan aman dengan jadwal survei fisik mandiri.': 'Dapatkan truk tangki, wingbox, trailer, cargo van, dan alat berat kualitas terbaik langsung dari ekosistem operasional Pancaran Logistics. Transparan, terpercaya, dan aman dengan jadwal survei fisik mandiri.',
    'KIR & STNK Lengkap': 'KIR & STNK Lengkap',
    'Bebas Atur Waktu Inspeksi': 'Bebas Atur Waktu Inspeksi',
    'Bagaimana Cara Kerja?': 'Bagaimana Cara Kerja?',
    'Pilih armada aktif di bawah, ajukan penawaran harga Anda, dan pilih waktu survei fisik untuk memeriksa kondisi mesin langsung di Pool kami sebelum lelang ditutup.': 'Pilih armada aktif di bawah, ajukan penawaran harga Anda, dan pilih waktu survei fisik untuk memeriksa kondisi mesin langsung di Pool kami sebelum lelang ditutup.',
    'Katalog Armada Tersedia': 'Katalog Armada Tersedia',
    'Semua armada di bawah siap dilepas dengan penawaran harga terbaik.': 'Semua armada di bawah siap dilepas dengan penawaran harga terbaik.',
    'Cari armada...': 'Cari armada...',
    'Tidak ada armada lelang yang terdaftar atau sesuai filter.': 'Tidak ada armada lelang yang terdaftar atau sesuai filter.',
    'Lihat Semua Koleksi': 'Lihat Semua Koleksi',
    'AJUKAN TAWAran': 'AJUKAN TAWAran',
    'Tutup Panel': 'Tutup Panel',
    'Harga Awal:': 'Harga Awal:',
    'Bid Tertinggi:': 'Bid Tertinggi:',
    'Spesifikasi & Deskripsi Aset': 'Spesifikasi & Deskripsi Aset',
    'Nama Lengkap Anda *': 'Nama Lengkap Anda *',
    'Contoh: PT Samudera Transport': 'Contoh: PT Samudera Transport',
    'Alamat Email Kontak *': 'Alamat Email Kontak *',
    'No. Handphone / WhatsApp *': 'No. Handphone / WhatsApp *',
    'Contoh: 0812XXXXXXXX': 'Contoh: 0812XXXXXXXX',
    'Harga Bid Anda (IDR) *': 'Harga Bid Anda (IDR) *',
    'Minimal harga bid:': 'Minimal harga bid:',
    'Booking Jadwal Survei Fisik': 'Booking Jadwal Survei Fisik',
    'Ingin cek kondisi mesin langsung di Pool?': 'Ingin cek kondisi mesin langsung di Pool?',
    'Tentukan Waktu Kunjungan Pool': 'Tentukan Waktu Kunjungan Pool',
    'Pilih Tanggal': 'Pilih Tanggal',
    'Pilih Sesi Jam': 'Pilih Sesi Jam',
    'Pagi Sesi 1 (09:00 WIB)': 'Pagi Sesi 1 (09:00 WIB)',
    'Pagi Sesi 2 (11:00 WIB)': 'Pagi Sesi 2 (11:00 WIB)',
    'Siang Sesi 1 (13:30 WIB)': 'Siang Sesi 1 (13:30 WIB)',
    'Sore Sesi 2 (15:30 WIB)': 'Sore Sesi 2 (15:30 WIB)',
    'Lokasi inspeksi:': 'Lokasi inspeksi:',
    'Tim teknis Pancaran Group akan mendampingi Anda di lokasi.': 'Tim teknis Pancaran Group akan mendampingi Anda di lokasi.',
    'Kirim Penawaran & Booking': 'Kirim Penawaran & Booking',
    'Penawaran Berhasil Dikirim!': 'Penawaran Berhasil Dikirim!',
    'Harga penawaran Anda telah dicatat ke dalam sistem Pancaran.': 'Harga penawaran Anda telah dicatat ke dalam sistem Pancaran.',
    'Armada:': 'Armada:',
    'Harga Bid Anda:': 'Harga Bid Anda:',
    'Jadwal Survei Fisik:': 'Jadwal Survei Fisik:',
    'Halaman ini akan kembali ke katalog dalam beberapa detik...': 'Halaman ini akan kembali ke katalog dalam beberapa detik...',
    'Dengan mengirimkan penawaran, Anda menyatakan tunduk pada Syarat & Ketentuan Umum Lelang Pancaran Logistics. Penawaran bersifat mengikat.': 'Dengan mengirimkan penawaran, Anda menyatakan tunduk pada Syarat & Ketentuan Umum Lelang Pancaran Logistics. Penawaran bersifat mengikat.',
  },
  en: {
    // General / Header / Footer
    'Pancaran Lelang': 'Pancaran Auctions',
    'Katalog Eksternal': 'External Catalog',
    'Katalog Eksternal (Public)': 'External Catalog (Public)',
    'Area Admin Internal': 'Internal Admin Area',
    'Login Admin': 'Admin Login',
    'Logout Admin': 'Admin Logout',
    'Admin Active': 'Admin Active',
    'Keluar': 'Logout',
    'Pilih Tampilan': 'Select View',
    'Menu Admin': 'Admin Menu',
    'Dashboard Ringkasan': 'Dashboard Summary',
    'Kelola Aset (Tambah & Bids)': 'Manage Assets (Add & Bids)',
    'Manajemen Akses': 'Access Management',
    'Status Koneksi': 'Connection Status',
    'Lelang Aktif': 'Active Auctions',
    'Sedang Berjalan': 'In Progress',
    'Unit Terjual': 'Sold Units',
    'Otorisasi Diperlukan': 'Authorization Required',
    'Halaman internal manajemen Pancaran Lelang dilindungi enkripsi. Silakan masuk menggunakan akun kredensial Anda.': 'The internal management page of Pancaran Lelang is protected by encryption. Please log in using your account credentials.',
    'Masuk Sekarang': 'Log In Now',
    'Hak Cipta Dilindungi': 'All Rights Reserved',
    'Pool Marunda': 'Marunda Pool',
    'Pool Cakung': 'Cakung Pool',
    'Pool Teluk Gong': 'Teluk Gong Pool',
    'Cilincing': 'Cilincing',
    'Admin Digital Solution': 'Digital Solution Admin',
    'AKUN MASUK:': 'LOGGED IN ACCOUNT:',
    'COMPANY INFO': 'COMPANY INFO',
    'Our Office': 'Our Office',
    'Head Office 1 :': 'Head Office 1 :',
    'HUBUNGI KAMI': 'CONTACT US',
    'Lokasi Pool Inspeksi:': 'Inspection Pool Locations:',
    'Portal resmi likuidasi armada aktif dan alat berat dari ekosistem operasional Pancaran Group. Transparan, tepercaya, dan terintegrasi.': 'Official portal for active fleet and heavy equipment liquidation from the Pancaran Group operational ecosystem. Transparent, trusted, and integrated.',
    'Syarat & Ketentuan': 'Terms & Conditions',
    'Kebijakan Privasi': 'Privacy Policy',

    // Catalog View & Cards
    'Cari aset lelang...': 'Search auction assets...',
    'Merek': 'Make',
    'Kategori': 'Category',
    'Kondisi': 'Condition',
    'Lokasi': 'Location',
    'Semua Merek': 'All Brands',
    'Semua Kategori': 'All Categories',
    'Semua Kondisi': 'All Conditions',
    'Semua Lokasi': 'All Locations',
    'Menampilkan {count} aset yang memenuhi kriteria': 'Showing {count} assets matching criteria',
    'Terbuka': 'Open',
    'Terjual': 'Sold',
    'Th': 'Yr',
    'Plat': 'Plate',
    'Harga Awal': 'Starting Price',
    'Harga Pembuka': 'Starting Price',
    'Penawaran Tertinggi': 'Highest Bid',
    'Belum ada penawaran': 'No bids yet',
    'Penawaran': 'Bid(s)',
    'Penawaran Masuk': 'Bid(s) Submitted',
    'Tawar Aset': 'Place Bid',
    'Brand:': 'Brand:',
    'Kategori:': 'Category:',
    'Tahun:': 'Year:',
    'No. Polisi:': 'License Plate:',
    'Kondisi:': 'Condition:',
    'Lokasi:': 'Location:',
    'Lihat Detail': 'View Details',
    'Lihat Detail & Ajukan Bid': 'View Details & Submit Bid',
    'Detail Unit Lelang': 'Auction Unit Details',
    'Kembali ke Katalog': 'Back to Catalog',
    'Spesifikasi Unit': 'Unit Specifications',
    'Tahun Pembuatan': 'Year of Manufacture',
    'Nomor Polisi': 'License Plate',
    'Kondisi Fisik': 'Physical Condition',
    'Deskripsi Tambahan': 'Additional Description',
    'Informasi & Tata Cara Lelang': 'Auction Information & Procedure',
    'Aset ini bersifat tangan pertama, memiliki dokumen legalitas (STNK, BPKB, KIR) lengkap dan siap dipindahtangankan setelah pelunasan.': 'This asset is first-hand, has complete legal documents (STNK, BPKB, KIR) and is ready to be transferred after full payment.',
    'Penawaran dilakukan secara terbuka. Setiap penawaran baru wajib lebih tinggi dari penawaran saat ini.': 'Bidding is conducted openly. Each new bid must be higher than the current bid.',
    'Setelah mengajukan penawaran, tim logistik kami akan menghubungi Anda untuk verifikasi dokumen dan penjadwalan inspeksi unit di lokasi pool terkait.': 'After placing a bid, our logistics team will contact you for document verification and scheduling unit inspections at the respective pool location.',
    'Riwayat Penawaran Saat Ini': 'Current Bid History',
    'Nama': 'Name',
    'Nilai Bid': 'Bid Value',
    'Waktu': 'Time',
    'Belum ada penawaran masuk untuk unit ini. Jadilah penawar pertama!': 'No bids received yet for this unit. Be the first bidder!',
    'Formulir Pengajuan Bid Resmi': 'Official Bid Submission Form',
    'Masukkan nama lengkap Anda...': 'Enter your full name...',
    'Contoh: 08123456789': 'Example: 08123456789',
    'Masukkan alamat email aktif...': 'Enter active email address...',
    'Rencana Tanggal Survey': 'Planned Survey Date',
    'Rencana Jam Survey': 'Planned Survey Time',
    'Harga Penawaran Anda (Rupiah)': 'Your Bid Price (Rupiah)',
    'Min. Penawaran Berikutnya:': 'Min. Next Bid:',
    'Kirim Penawaran & Jadwalkan Survey': 'Submit Bid & Schedule Survey',
    'Memproses...': 'Processing...',
    'Silakan isi semua data dengan benar.': 'Please fill all fields correctly.',
    'Penawaran Anda harus lebih besar dari penawaran tertinggi saat ini!': 'Your bid must be higher than the current highest bid!',
    'Penawaran Anda Berhasil Dikirim!': 'Your Bid Successfully Submitted!',
    'Terima kasih telah mengajukan penawaran. Tim Pancaran Logistic akan segera menghubungi Anda di nomor kontak yang tertera.': 'Thank you for submitting a bid. The Pancaran Logistics team will contact you shortly at the provided contact details.',
    'Tutup': 'Close',
    'Pemenang Lelang': 'Auction Winner',
    'Pemenang': 'Winner',
    'Penawaran Pemenang': 'Winning Bid',
    'Kontak Pemenang': 'Winner Contact',
    'Belum ada penawar': 'No bidders yet',
    'Perkecil': 'Zoom Out',
    'Perbesar / Fokus Detail': 'Zoom In / Focus Detail',
    'Seret/Scroll untuk melihat bagian gambar • Klik gambar untuk mengecilkan': 'Drag/Scroll to view parts of the image • Click image to zoom out',
    'Klik gambar atau tombol untuk memperbesar penuh & jelas': 'Click image or button to zoom in full & clear',
    'Sudah Dibooking': 'Already Booked',
    'Pilih Tanggal Kunjungan': 'Select Visit Date',
    'Pilih Sesi Jam Kunjungan': 'Select Visit Session',
    'Ready': 'Ready',
    'Selected': 'Selected',
    'Booked': 'Booked',
    'Sesi Pagi I': 'Morning Session I',
    'Sesi Pagi II': 'Morning Session II',
    'Sesi Siang I': 'Afternoon Session I',
    'Sesi Sore II': 'Afternoon Session II',
    'Informasi Lokasi & Pendampingan': 'Location & Assistance Information',
    'Jadwal survei pada tanggal dan jam tersebut sudah di-booking oleh calon pembeli lain. Mohon pilih waktu atau hari lain.': 'The survey schedule for that date and time has been booked by another prospective buyer. Please choose another time or day.',
    'Klik gambar untuk berikutnya • Klik di luar untuk kembali': 'Click image for next • Click outside to go back',
    'Klik gambar atau di luar untuk kembali': 'Click image or outside to go back',
    'Klik gambar untuk memperkecil • Geser untuk menjelajah detail': 'Click image to zoom out • Scroll/pan to explore details',
    'Klik gambar untuk memperbesar • Klik di luar untuk kembali': 'Click image to zoom in • Click outside to go back',
    'Zoom In': 'Zoom In',
    'Zoom Out': 'Zoom Out',

    // Login Modal
    'Otoritas Internal Admin': 'Internal Admin Authority',
    'Gunakan email & password terdaftar untuk mengelola sistem lelang.': 'Use registered email & password to manage the auction system.',
    'Email atau password salah. Pastikan kredensial benar.': 'Incorrect email or password. Please ensure credentials are correct.',
    'ALAMAT EMAIL KERJA': 'WORK EMAIL ADDRESS',
    'KATA SANDI (PASSWORD)': 'PASSWORD',
    'Masuk Aplikasi': 'Enter Application',
    'Petunjuk Akun Penguji:': 'Tester Account Tips:',
    'Untuk menguji fitur admin, silakan klik tombol di bawah untuk mengisi kredensial default dari user secara instan.': 'To test admin features, click the button below to instantly fill default credentials.',
    'Isi Kredensial Penguji': 'Fill Tester Credentials',

    // Admin Dashboard
    'Dashboard Utama & Analitik': 'Main Dashboard & Analytics',
    'Ringkasan metrik performa sistem lelang Pancaran Logistics secara real-time.': 'Real-time summary of Pancaran Logistics auction system performance metrics.',
    'Total Asset': 'Total Assets',
    'Unit di Database': 'Units in Database',
    'Sedang Aktif': 'Currently Active',
    'Menerima Penawaran': 'Accepting Bids',
    'Aset Terjual': 'Assets Sold',
    'Sudah Diproses': 'Processed',
    'Total Bidder': 'Total Bidders',
    'Telah Berpartisipasi': 'Have Participated',
    'Aset Terpopuler': 'Most Popular Asset',
    'Dengan Penawaran Terbanyak': 'With Most Bids',
    'Daftar Aktivitas Bid Terbaru': 'Recent Bid Activity List',
    'Aktivitas Terbaru': 'Recent Activity',
    'Daftar pengajuan penawaran harga dari calon pembeli eksternal.': 'List of price bid submissions from external prospective buyers.',
    'Semua Riwayat': 'All History',
    'Aset': 'Asset',
    'Penawar': 'Bidder',
    'Jumlah Penawaran': 'Bid Amount',
    'Tanggal & Waktu': 'Date & Time',
    'Status': 'Status',
    'Tindakan': 'Actions',
    'Belum ada aktivitas penawaran yang terdaftar di sistem.': 'No bid activity registered in the system yet.',
    'Lihat Detail Aset': 'View Asset Details',

    // Admin Assets
    'Daftar Manajemen Aset': 'Asset Management List',
    'Kelola unit logistik yang dilelang, tambahkan unit baru, dan pantau histori penawaran masuk.': 'Manage auctioned logistics units, add new units, and monitor incoming bid history.',
    'Tambah Unit Baru': 'Add New Unit',
    'Daftarkan Aset Lelang Baru': 'Register New Auction Asset',
    'Lengkapi spesifikasi teknis dan detail dokumen kendaraan di bawah.': 'Complete technical specifications and vehicle document details below.',
    'Ubah Detail Unit': 'Edit Unit Details',
    'Perbarui spesifikasi teknis dan kelengkapan dokumen kendaraan lelang.': 'Update technical specifications and completeness of auction vehicle documents.',
    'Semua Aset': 'All Assets',
    'Aktif / Open': 'Active / Open',
    'Terjual / Sold': 'Sold / Closed',
    'Cari aset...': 'Search assets...',
    'Tipe': 'Type',
    'Aksi': 'Actions',
    'Belum ada aset lelang yang cocok dengan pencarian Anda.': 'No auction assets match your search.',
    'PILIH TEMPLATE KENDARAAN (OPSIONAL)': 'SELECT VEHICLE TEMPLATE (OPTIONAL)',
    'Memilih template akan otomatis mengisi Nama, Brand, Kategori, dan gambar ilustrasi standar.': 'Selecting a template will automatically populate Name, Brand, Category, and standard illustration.',
    'FORMULIR MANAJEMEN UNIT ASET': 'UNIT ASSET MANAGEMENT FORM',
    'Nama Kendaraan / Aset': 'Vehicle / Asset Name',
    'Merek / Brand': 'Make / Brand',
    'Kategori Kendaraan': 'Vehicle Category',
    'Tahun': 'Year',
    'Nomor Registrasi (Plat)': 'Registration Number (Plate)',
    'Sangat Baik': 'Excellent',
    'Baik': 'Good',
    'Cukup': 'Fair',
    'Butuh Perbaikan': 'Needs Repair',
    'Lokasi Pool': 'Pool Location',
    'Harga Awal (IDR)': 'Starting Price (IDR)',
    'Deskripsi & Spesifikasi Tambahan': 'Description & Additional Specs',
    'Batal': 'Cancel',
    'Simpan Perubahan': 'Save Changes',
    'Tambah Unit ke Sistem': 'Add Unit to System',
    'Unggah Foto Unit': 'Upload Unit Photo',
    'Klik untuk unggah atau seret foto ke sini': 'Click to upload or drag photo here',
    'Format JPG, PNG maks 5MB. Gambar akan otomatis dikompresi untuk performa optimal.': 'Format JPG, PNG max 5MB. Image will be automatically compressed for optimal performance.',
    'Foto berhasil diunggah': 'Photo successfully uploaded',
    'Hapus Foto': 'Delete Photo',
    'Gambar Utama': 'Primary Image',
    'PILIH ALAT BANTU': 'CHOOSE UTILITIES',
    'Dapatkan Saran Deskripsi dengan AI': 'Get Description Suggestions with AI',
    'Saran Deskripsi': 'Description Suggestions',
    'Gunakan Saran AI': 'Use AI Suggestion',
    'Silakan pilih template atau isi Brand & Kategori terlebih dahulu agar AI dapat menganalisis deskripsi yang relevan.': 'Please select a template or fill in the Brand & Category first so that the AI can analyze relevant descriptions.',
    'Detail Histori Penawaran': 'Bid History Details',
    'Pilih aset di sebelah kiri untuk melihat detail spesifikasi dan histori penawaran secara menyeluruh.': 'Select an asset on the left to view detailed specifications and full bid history.',
    'Detail Spesifikasi': 'Specification Details',
    'Histori Bid': 'Bid History',
    'Ubah Atribut': 'Edit Attributes',
    'Ubah Status': 'Edit Status',
    'Buka Penawaran': 'Open Bidding',
    'Tutup / Selesaikan (Sold)': 'Close / Complete (Sold)',
    'Hapus Unit': 'Delete Unit',
    'Apakah Anda yakin ingin menghapus aset ini secara permanen dari sistem database?': 'Are you sure you want to permanently delete this asset from the database system?',
    'Ya, Hapus': 'Yes, Delete',
    'Tidak': 'No',
    'Rencana Survey:': 'Planned Survey:',
    'Belum ada penawaran untuk unit ini.': 'No bids for this unit.',
    'Bids Masuk': 'Incoming Bids',
    'Hubungi': 'Contact',

    // Additional Admin Assets Dialogs & Details
    'PLAT NOMOR': 'LICENSE PLATE',
    'TAHUN PRODUKSI': 'YEAR OF MANUFACTURE',
    'KONDISI FISIK': 'PHYSICAL CONDITION',
    'LOKASI SEEDING': 'POOL LOCATION',
    'DESKRIPSI INTERNAL': 'INTERNAL DESCRIPTION',
    'Histori Penawaran': 'Bid History',
    'Bids Tertinggi Pertama': 'Highest Bids First',
    'Jadwal Survei': 'Survey Schedule',
    'Belum ada penawaran harga masuk untuk aset ini.': 'No bids have been submitted for this asset yet.',
    'Konfirmasi Hapus Unit': 'Confirm Asset Deletion',
    'Edit Unit Aset': 'Edit Asset Unit',
    'Hapus Unit Aset': 'Delete Asset Unit',
    'Tutup Detail': 'Close Details',
    'Status Lelang Saat Ini:': 'Current Auction Status:',
    'Menerima Bid': 'Accepting Bids',
    'Buka Bid': 'Open Bidding',
    'Set Terjual': 'Set as Sold',
    'Sebelumnya': 'Previous',
    'Berikutnya': 'Next',
    'Tambah': 'Add',
    'Ketik atau tempel tautan gambar, lalu tekan tombol "Tambah" atau Enter untuk memasukkan ke galeri unit lelang ini.': 'Type or paste an image link, then press the "Add" button or Enter to add it to the gallery.',
    'Simpan Unit Baru': 'Save New Unit',
    'Kelola Aset Lelang': 'Manage Auction Assets',
    'Daftarkan armada logistik baru, pantau status lelang, dan verifikasi riwayat penawaran.': 'Register new logistics fleets, monitor auction statuses, and verify bid history.',
    'Tambah Aset Baru': 'Add New Asset',
    'Cari berdasarkan nama aset, plat, kategori...': 'Search by asset name, plate, category...',
    'Semua Brand': 'All Brands',
    'Tidak ada aset lelang yang cocok dengan kriteria pencarian.': 'No auction assets match your search criteria.',
    'Reset Semua Filter': 'Reset All Filters',
    'Merek (Brand) *': 'Make (Brand) *',
    'Kategori Unit *': 'Unit Category *',
    'Tahun Produksi *': 'Production Year *',
    'No. Registrasi / Plat Nomor': 'Registration No. / Plate Number',
    'Kondisi Fisik Unit *': 'Physical Condition *',
    'Harga Awal Lelang (IDR) *': 'Starting Price (IDR) *',
    'Lokasi Pool / Depo Unit *': 'Pool / Depot Location *',
    'Foto / Gambar Unit * (Bisa Unggah Banyak)': 'Unit Photos * (Supports Multiple Uploads)',
    'Pilih atau Seret Foto-Foto Armada': 'Select or Drag Fleet Photos',
    'Mendukung format PNG, JPG, JPEG (Bisa pilih banyak sekaligus, Max 5MB per file)': 'Supports PNG, JPG, JPEG formats (Can select multiple at once, Max 5MB per file)',
    'Koleksi Foto Terunggah ({count})': 'Uploaded Photo Gallery ({count})',
    'Cover Utama': 'Main Cover',
    'Tambah Foto via Tautan Gambar (URL)': 'Add Photo via Image Link (URL)',
    'Apakah Anda yakin ingin menghapus {name} secara permanen? Data historis penawaran juga akan ikut terhapus.': 'Are you sure you want to permanently delete {name}? Historical bid data will also be deleted.',

    // Admin Users
    'Kelola Hak Akses Admin': 'Manage Admin Privileges',
    'Tambahkan, hapus, dan atur peran pengguna internal yang dapat masuk ke dashboard administrasi.': 'Add, remove, and manage internal users who can access the administration dashboard.',
    'Daftarkan Admin Baru': 'Register New Admin',
    'Nama Lengkap': 'Full Name',
    'Alamat Email Pancaran': 'Pancaran Email Address',
    'Peran / Hak Akses': 'Role / Access Rights',
    'Super Admin': 'Super Admin',
    'Admin Operasional': 'Operational Admin',
    'Admin Keuangan': 'Financial Admin',
    'Daftarkan': 'Register',
    'Akun Terdaftar': 'Registered Accounts',
    'Peran': 'Role',
    'Bergabung': 'Joined',
    'Anda': 'You',
    'Hapus Akses': 'Revoke Access',
    'Apakah Anda yakin ingin menghapus hak akses untuk admin ini?': 'Are you sure you want to revoke access rights for this admin?',

    // Additional Admin Users Keys
    'Manajemen Akses Admin': 'Admin Access Management',
    'Buat akses administrator baru, tinjau tingkatan hak akses, dan kelola otoritas keamanan internal Pancaran Lelang.': 'Create new administrator access, review privilege levels, and manage internal security authority for Pancaran Auctions.',
    'Buat Akses Baru': 'Create New Access',
    'Daftarkan akun email karyawan baru untuk memberikan akses masuk ke dashboard internal.': 'Register a new employee email account to grant access to the internal dashboard.',
    'Nama Lengkap Admin': 'Admin Full Name',
    'Contoh: Achmad Subagja': 'Example: Achmad Subagja',
    'Harus berupa email institusi Pancaran.': 'Must be an official Pancaran email.',
    'Tingkatan Peran (Role)': 'Role / Privilege Level',
    'Admin Operasional (Input & Kelola Aset)': 'Operational Admin (Input & Manage Assets)',
    'Admin Keuangan (Otorisasi Unit Terjual)': 'Financial Admin (Authorize Sold Units)',
    'Super Admin (Akses Penuh)': 'Super Admin (Full Access)',
    'Buat Hak Akses': 'Grant Access Rights',
    'Daftar Administrator Terdaftar': 'Registered Administrator List',
    'Daftar staf internal Pancaran Logistics yang memegang otoritas sistem Lelang.': 'List of internal Pancaran Logistics staff holding auction system authority.',
    'Nama / Karyawan': 'Name / Employee',
    'Email Akun': 'Account Email',
    'Terdaftar Pada': 'Registered On',
    'Ya': 'Yes',
    'Mohon lengkapi nama dan email admin.': 'Please complete the admin name and email fields.',
    'Email admin tersebut sudah terdaftar.': 'That admin email is already registered.',
    'Format email tidak valid. Direkomendasikan menggunakan email institusi Pancaran.': 'Invalid email format. It is recommended to use official Pancaran emails.',
    'Akses admin berhasil dibuat untuk': 'Admin access successfully created for',
    'Anda sedang masuk dengan akun ini': 'You are currently logged in with this account',
    'Akun Super Admin Utama tidak bisa dihapus': 'The primary Super Admin account cannot be deleted',

    // New keys for Admin Dashboard and other pages
    'Dashboard Pancaran Lelang': 'Pancaran Auctions Dashboard',
    'Halo Admin, kelola aset lelang komersial, pantau penawaran harga, dan atur survei fisik dalam satu portal terpadu.': 'Hello Admin, manage commercial auction assets, monitor price bids, and organize physical surveys in one integrated portal.',
    'Waktu Sistem (WIB)': 'System Time (WIB)',
    'Sukses Lelang': 'Auction Success',
    'Aset Aktif': 'Active Assets',
    'Partisipan Unik': 'Unique Participants',
    'Total Aset per Brand': 'Total Assets per Brand',
    'Porsi distribusi armada lelang Pancaran Logistics berdasarkan merek manufaktur.': "Distribution share of Pancaran Logistics' auction fleet based on manufacturing brands.",
    'Unit': 'Units',
    'Belum ada data armada/brand tersedia.': 'No fleet/brand data available yet.',
    'Per 2026. Semua aset fisik di pool internal.': 'As of 2026. All physical assets located in internal pools.',
    'Jadwal Survei Fisik': 'Physical Survey Schedule',
    'Daftar booking kunjungan calon pembeli untuk inspeksi fisik kendaraan.': 'Booking list of prospective buyers visiting for physical vehicle inspection.',
    'Semua': 'All',
    'Mendatang': 'Upcoming',
    'Riwayat': 'History',
    'Cari nama bidder, brand, atau armada...': 'Search bidder name, brand, or fleet...',
    'Selesai': 'Completed',
    'Bidder': 'Bidder',
    'Lihat Aset': 'View Asset',
    'Tidak ada jadwal survei fisik ditemukan.': 'No physical survey schedule found.',

    // Public Catalog & Banner Keys
    'Portal Penawaran Umum (External)': 'Public Bidding Portal (External)',
    'Likuidasi Armada Logistik & Heavy Equipment': 'Liquidation of Logistics Fleet & Heavy Equipment',
    'Dapatkan truk tangki, wingbox, trailer, cargo van, dan alat berat kualitas terbaik langsung dari ekosistem operasional Pancaran Logistics. Transparan, terpercaya, dan aman dengan jadwal survei fisik mandiri.': 'Get the best quality tank trucks, wingboxes, trailers, cargo vans, and heavy equipment directly from the operational ecosystem of Pancaran Logistics. Transparent, reliable, and secure with self-scheduled physical surveys.',
    'KIR & STNK Lengkap': 'Complete KIR & STNK Registration',
    'Bebas Atur Waktu Inspeksi': 'Flexible Inspection Scheduling',
    'Bagaimana Cara Kerja?': 'How It Works',
    'Pilih armada aktif di bawah, ajukan penawaran harga Anda, dan pilih waktu survei fisik untuk memeriksa kondisi mesin langsung di Pool kami sebelum lelang ditutup.': 'Select an active fleet below, submit your price bid, and select a physical survey time to inspect the engine directly at our pool before the bidding closes.',
    'Katalog Armada Tersedia': 'Available Fleet Catalog',
    'Semua armada di bawah siap dilepas dengan penawaran harga terbaik.': 'All fleets below are ready to be released with the best price bids.',
    'Cari armada...': 'Search fleet...',
    'Tidak ada armada lelang yang terdaftar atau sesuai filter.': 'No auction fleets registered or matching the filter.',
    'Lihat Semua Koleksi': 'View All Collections',
    'AJUKAN TAWAran': 'SUBMIT OFFER',
    'Tutup Panel': 'Close Panel',
    'Harga Awal:': 'Starting Price:',
    'Bid Tertinggi:': 'Highest Bid:',
    'Spesifikasi & Deskripsi Aset': 'Asset Specifications & Description',
    'Nama Lengkap Anda *': 'Your Full Name *',
    'Contoh: PT Samudera Transport': 'Example: PT Samudera Transport',
    'Alamat Email Kontak *': 'Contact Email Address *',
    'No. Handphone / WhatsApp *': 'Mobile / WhatsApp Number *',
    'Contoh: 0812XXXXXXXX': 'Example: 0812XXXXXXXX',
    'Harga Bid Anda (IDR) *': 'Your Bid Price (IDR) *',
    'Minimal harga bid:': 'Minimum bid price:',
    'Booking Jadwal Survei Fisik': 'Book Physical Survey Schedule',
    'Ingin cek kondisi mesin langsung di Pool?': 'Want to check the engine condition directly at the Pool?',
    'Tentukan Waktu Kunjungan Pool': 'Determine Pool Visit Time',
    'Pilih Tanggal': 'Select Date',
    'Pilih Sesi Jam': 'Select Time Session',
    'Pagi Sesi 1 (09:00 WIB)': 'Morning Session 1 (09:00 WIB)',
    'Pagi Sesi 2 (11:00 WIB)': 'Morning Session 2 (11:00 WIB)',
    'Siang Sesi 1 (13:30 WIB)': 'Afternoon Session 1 (13:30 WIB)',
    'Sore Sesi 2 (15:30 WIB)': 'Late Afternoon Session 2 (15:30 WIB)',
    'Lokasi inspeksi:': 'Inspection location:',
    'Tim teknis Pancaran Group akan mendampingi Anda di lokasi.': 'The Pancaran Group technical team will assist you on site.',
    'Kirim Penawaran & Booking': 'Submit Bid & Book',
    'Penawaran Berhasil Dikirim!': 'Bid Successfully Submitted!',
    'Harga penawaran Anda telah dicatat ke dalam sistem Pancaran.': 'Your bid price has been recorded into the Pancaran system.',
    'Armada:': 'Fleet:',
    'Harga Bid Anda:': 'Your Bid Price:',
    'Jadwal Survei Fisik:': 'Physical Survey Schedule:',
    'Halaman ini akan kembali ke katalog dalam beberapa detik...': 'This page will return to the catalog in a few seconds...',
    'Dengan mengirimkan penawaran, Anda menyatakan tunduk pada Syarat & Ketentuan Umum Lelang Pancaran Logistics. Penawaran bersifat mengikat.': 'By submitting an offer, you agree to the General Terms & Conditions of Pancaran Logistics Auctions. Bids are binding.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string, variables?: Record<string, string | number>): string => {
    const translationSet = translations[language];
    let text = translationSet[key] || translations['id'][key] || key;

    if (variables) {
      Object.entries(variables).forEach(([vKey, vVal]) => {
        text = text.replace(`{${vKey}}`, String(vVal));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
