import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'id' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, variables?: Record<string, string | number>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  id: {
    // General / Header / Footer
    'Pancaran Lelang': 'Pancaran Lelang',
    'Katalog Eksternal': 'Katalog Eksternal',
    'Katalog Eksternal (Public)': 'Katalog Eksternal (Publik)',
    'Area Admin Internal': 'Area Admin Internal',
    'Login Admin': 'Login Admin',
    'Logout Admin': 'Keluar Admin',
    'Admin Active': 'Admin Aktif',
    'Keluar': 'Keluar',
    'Pilih Tampilan': 'Pilih Tampilan',
    'Menu Admin': 'Menu Admin',
    'Dashboard Ringkasan': 'Dashboard Ringkasan',
    'Kelola Aset (Tambah & Bids)': 'Kelola Aset (Tambah & Bids)',
    'Manajemen Akses': 'Manajemen Akses',
    'Status Koneksi': 'Status Koneksi',
    'Lelang Aktif': 'Lelang Aktif',
    'Sedang Berjalan': 'Sedang Berjalan',
    'Unit Terjual': 'Unit Terjual',
    'Otorisasi Diperlukan': 'Otorisasi Diperlukan',
    'Halaman internal manajemen Pancaran Lelang dilindungi enkripsi. Silakan masuk menggunakan akun kredensial Anda.': 'Halaman internal manajemen Pancaran Lelang dilindungi enkripsi. Silakan masuk menggunakan akun kredensial Anda.',
    'Masuk Sekarang': 'Masuk Sekarang',
    'Hak Cipta Dilindungi': 'Hak Cipta Dilindungi',
    'Pool Marunda': 'Pool Marunda',
    'Pool Cakung': 'Pool Cakung',
    'Pool Teluk Gong': 'Pool Teluk Gong',
    'Admin Digital Solution': 'Admin Digital Solution',
    'AKUN MASUK:': 'AKUN MASUK:',

    // Catalog View & Cards
    'Cari aset lelang...': 'Cari aset lelang...',
    'Merek': 'Merek',
    'Kategori': 'Kategori',
    'Kondisi': 'Kondisi',
    'Lokasi': 'Lokasi',
    'Semua Merek': 'Semua Merek',
    'Semua Kategori': 'Semua Kategori',
    'Semua Kondisi': 'Semua Kondisi',
    'Semua Lokasi': 'Semua Lokasi',
    'Menampilkan {count} aset yang memenuhi kriteria': 'Menampilkan {count} aset yang memenuhi kriteria',
    'Terbuka': 'Terbuka',
    'Terjual': 'Terjual',
    'Th': 'Th',
    'Harga Pembuka': 'Harga Pembuka',
    'Penawaran Tertinggi': 'Penawaran Tertinggi',
    'Belum ada penawaran': 'Belum ada penawaran',
    'Penawaran': 'Penawaran',
    'Lihat Detail': 'Lihat Detail',
    'Lihat Detail & Ajukan Bid': 'Lihat Detail & Ajukan Bid',
    'Detail Unit Lelang': 'Detail Unit Lelang',
    'Kembali ke Katalog': 'Kembali ke Katalog',
    'Spesifikasi Unit': 'Spesifikasi Unit',
    'Tahun Pembuatan': 'Tahun Pembuatan',
    'Nomor Polisi': 'Nomor Polisi',
    'Kondisi Fisik': 'Kondisi Fisik',
    'Deskripsi Tambahan': 'Deskripsi Tambahan',
    'Informasi & Tata Cara Lelang': 'Informasi & Tata Cara Lelang',
    'Aset ini bersifat tangan pertama, memiliki dokumen legalitas (STNK, BPKB, KIR) lengkap dan siap dipindahtangankan setelah pelunasan.': 'Aset ini bersifat tangan pertama, memiliki dokumen legalitas (STNK, BPKB, KIR) lengkap dan siap dipindahtangankan setelah pelunasan.',
    'Penawaran dilakukan secara terbuka. Setiap penawaran baru wajib lebih tinggi dari penawaran saat ini.': 'Penawaran dilakukan secara terbuka. Setiap penawaran baru wajib lebih tinggi dari penawaran saat ini.',
    'Setelah mengajukan penawaran, tim logistik kami akan menghubungi Anda untuk verifikasi dokumen dan penjadwalan inspeksi unit di lokasi pool terkait.': 'Setelah mengajukan penawaran, tim logistik kami akan menghubungi Anda untuk verifikasi dokumen dan penjadwalan inspeksi unit di lokasi pool terkait.',
    'Riwayat Penawaran Saat Ini': 'Riwayat Penawaran Saat Ini',
    'Nama': 'Nama',
    'Nilai Bid': 'Nilai Bid',
    'Waktu': 'Waktu',
    'Belum ada penawaran masuk untuk unit ini. Jadilah penawar pertama!': 'Belum ada penawaran masuk untuk unit ini. Jadilah penawar pertama!',
    'Formulir Pengajuan Bid Resmi': 'Formulir Pengajuan Bid Resmi',
    'Masukkan nama lengkap Anda...': 'Masukkan nama lengkap Anda...',
    'Contoh: 08123456789': 'Contoh: 08123456789',
    'Masukkan alamat email aktif...': 'Masukkan alamat email aktif...',
    'Rencana Tanggal Survey': 'Rencana Tanggal Survey',
    'Rencana Jam Survey': 'Rencana Jam Survey',
    'Harga Penawaran Anda (Rupiah)': 'Harga Penawaran Anda (Rupiah)',
    'Min. Penawaran Berikutnya:': 'Min. Penawaran Berikutnya:',
    'Kirim Penawaran & Jadwalkan Survey': 'Kirim Penawaran & Jadwalkan Survey',
    'Memproses...': 'Memproses...',
    'Silakan isi semua data dengan benar.': 'Silakan isi semua data dengan benar.',
    'Penawaran Anda harus lebih besar dari penawaran tertinggi saat ini!': 'Penawaran Anda harus lebih besar dari penawaran tertinggi saat ini!',
    'Penawaran Anda Berhasil Dikirim!': 'Penawaran Anda Berhasil Dikirim!',
    'Terima kasih telah mengajukan penawaran. Tim Pancaran Logistic akan segera menghubungi Anda di nomor kontak yang tertera.': 'Terima kasih telah mengajukan penawaran. Tim Pancaran Logistic akan segera menghubungi Anda di nomor kontak yang tertera.',
    'Tutup': 'Tutup',

    // Login Modal
    'Otoritas Internal Admin': 'Otoritas Internal Admin',
    'Gunakan email & password terdaftar untuk mengelola sistem lelang.': 'Gunakan email & password terdaftar untuk mengelola sistem lelang.',
    'Email atau password salah. Pastikan kredensial benar.': 'Email atau password salah. Pastikan kredensial benar.',
    'ALAMAT EMAIL KERJA': 'ALAMAT EMAIL KERJA',
    'KATA SANDI (PASSWORD)': 'KATA SANDI (PASSWORD)',
    'Masuk Aplikasi': 'Masuk Aplikasi',
    'Petunjuk Akun Penguji:': 'Petunjuk Akun Penguji:',
    'Untuk menguji fitur admin, silakan klik tombol di bawah untuk mengisi kredensial default dari user secara instan.': 'Untuk menguji fitur admin, silakan klik tombol di bawah untuk mengisi kredensial default dari user secara instan.',
    'Isi Kredensial Penguji': 'Isi Kredensial Penguji',

    // Admin Dashboard
    'Dashboard Utama & Analitik': 'Dashboard Utama & Analitik',
    'Ringkasan metrik performa sistem lelang Pancaran Logistics secara real-time.': 'Ringkasan metrik performa sistem lelang Pancaran Logistics secara real-time.',
    'Total Asset': 'Total Aset',
    'Unit di Database': 'Unit di Database',
    'Sedang Aktif': 'Sedang Aktif',
    'Menerima Penawaran': 'Menerima Penawaran',
    'Aset Terjual': 'Aset Terjual',
    'Sudah Diproses': 'Sudah Diproses',
    'Total Bidder': 'Total Penawar',
    'Telah Berpartisipasi': 'Telah Berpartisipasi',
    'Aset Terpopuler': 'Aset Terpopuler',
    'Dengan Penawaran Terbanyak': 'Dengan Penawaran Terbanyak',
    'Daftar Aktivitas Bid Terbaru': 'Daftar Aktivitas Bid Terbaru',
    'Aktivitas Terbaru': 'Aktivitas Terbaru',
    'Daftar pengajuan penawaran harga dari calon pembeli eksternal.': 'Daftar pengajuan penawaran harga dari calon pembeli eksternal.',
    'Semua Riwayat': 'Semua Riwayat',
    'Aset': 'Aset',
    'Penawar': 'Penawar',
    'Jumlah Penawaran': 'Jumlah Penawaran',
    'Tanggal & Waktu': 'Tanggal & Waktu',
    'Status': 'Status',
    'Tindakan': 'Tindakan',
    'Belum ada aktivitas penawaran yang terdaftar di sistem.': 'Belum ada aktivitas penawaran yang terdaftar di sistem.',
    'Lihat Detail Aset': 'Lihat Detail Aset',

    // Admin Assets
    'Daftar Manajemen Aset': 'Daftar Manajemen Aset',
    'Kelola unit logistik yang dilelang, tambahkan unit baru, dan pantau histori penawaran masuk.': 'Kelola unit logistik yang dilelang, tambahkan unit baru, dan pantau histori penawaran masuk.',
    'Tambah Unit Baru': 'Tambah Unit Baru',
    'Semua Aset': 'Semua Aset',
    'Aktif / Open': 'Aktif / Open',
    'Terjual / Sold': 'Terjual / Sold',
    'Cari aset...': 'Cari aset...',
    'Tipe': 'Tipe',
    'Aksi': 'Aksi',
    'Belum ada aset lelang yang cocok dengan pencarian Anda.': 'Belum ada aset lelang yang cocok dengan pencarian Anda.',
    'PILIH TEMPLATE KENDARAAN (OPSIONAL)': 'PILIH TEMPLATE KENDARAAN (OPSIONAL)',
    'Memilih template akan otomatis mengisi Nama, Brand, Kategori, dan gambar ilustrasi standar.': 'Memilih template akan otomatis mengisi Nama, Brand, Kategori, dan gambar ilustrasi standar.',
    'FORMULIR MANAJEMEN UNIT ASET': 'FORMULIR MANAJEMEN UNIT ASET',
    'Nama Kendaraan / Aset': 'Nama Kendaraan / Aset',
    'Merek / Brand': 'Merek / Brand',
    'Kategori Kendaraan': 'Kategori Kendaraan',
    'Tahun': 'Tahun',
    'Nomor Registrasi (Plat)': 'Nomor Registrasi (Plat)',
    'Sangat Baik': 'Sangat Baik',
    'Baik': 'Baik',
    'Cukup': 'Cukup',
    'Butuh Perbaikan': 'Butuh Perbaikan',
    'Lokasi Pool': 'Lokasi Pool',
    'Harga Awal (IDR)': 'Harga Awal (IDR)',
    'Deskripsi & Spesifikasi Tambahan': 'Deskripsi & Spesifikasi Tambahan',
    'Batal': 'Batal',
    'Simpan Perubahan': 'Simpan Perubahan',
    'Tambah Unit ke Sistem': 'Tambah Unit ke Sistem',
    'Unggah Foto Unit': 'Unggah Foto Unit',
    'Klik untuk unggah atau seret foto ke sini': 'Klik untuk unggah atau seret foto ke sini',
    'Format JPG, PNG maks 5MB. Gambar akan otomatis dikompresi untuk performa optimal.': 'Format JPG, PNG maks 5MB. Gambar akan otomatis dikompresi untuk performa optimal.',
    'Foto berhasil diunggah': 'Foto berhasil diunggah',
    'Hapus Foto': 'Hapus Foto',
    'Gambar Utama': 'Gambar Utama',
    'PILIH ALAT BANTU': 'PILIH ALAT BANTU',
    'Dapatkan Saran Deskripsi dengan AI': 'Dapatkan Saran Deskripsi dengan AI',
    'Saran Deskripsi': 'Saran Deskripsi',
    'Gunakan Saran AI': 'Gunakan Saran AI',
    'Silakan pilih template atau isi Brand & Kategori terlebih dahulu agar AI dapat menganalisis deskripsi yang relevan.': 'Silakan pilih template atau isi Brand & Kategori terlebih dahulu agar AI dapat menganalisis deskripsi yang relevan.',
    'Detail Histori Penawaran': 'Detail Histori Penawaran',
    'Pilih aset di sebelah kiri untuk melihat detail spesifikasi dan histori penawaran secara menyeluruh.': 'Pilih aset di sebelah kiri untuk melihat detail spesifikasi dan histori penawaran secara menyeluruh.',
    'Detail Spesifikasi': 'Detail Spesifikasi',
    'Histori Bid': 'Histori Bid',
    'Ubah Atribut': 'Ubah Atribut',
    'Ubah Status': 'Ubah Status',
    'Buka Penawaran': 'Buka Penawaran',
    'Tutup / Selesaikan (Sold)': 'Tutup / Selesaikan (Sold)',
    'Hapus Unit': 'Hapus Unit',
    'Apakah Anda yakin ingin menghapus aset ini secara permanen dari sistem database?': 'Apakah Anda yakin ingin menghapus aset ini secara permanen dari sistem database?',
    'Ya, Hapus': 'Ya, Hapus',
    'Tidak': 'Tidak',
    'Rencana Survey:': 'Rencana Survey:',
    'Belum ada penawaran untuk unit ini.': 'Belum ada penawaran untuk unit ini.',
    'Bids Masuk': 'Bids Masuk',
    'Hubungi': 'Hubungi',

    // Admin Users
    'Kelola Hak Akses Admin': 'Kelola Hak Akses Admin',
    'Tambahkan, hapus, dan atur peran pengguna internal yang dapat masuk ke dashboard administrasi.': 'Tambahkan, hapus, dan atur peran pengguna internal yang dapat masuk ke dashboard administrasi.',
    'Daftarkan Admin Baru': 'Daftarkan Admin Baru',
    'Nama Lengkap': 'Nama Lengkap',
    'Alamat Email Pancaran': 'Alamat Email Pancaran',
    'Peran / Hak Akses': 'Peran / Hak Akses',
    'Super Admin': 'Super Admin',
    'Admin Operasional': 'Admin Operasional',
    'Admin Keuangan': 'Admin Keuangan',
    'Daftarkan': 'Daftarkan',
    'Akun Terdaftar': 'Akun Terdaftar',
    'Peran': 'Peran',
    'Bergabung': 'Bergabung',
    'Anda': 'Anda',
    'Hapus Akses': 'Hapus Akses',
    'Apakah Anda yakin ingin menghapus hak akses untuk admin ini?': 'Apakah Anda yakin ingin menghapus hak akses untuk admin ini?',
  },
  en: {
    // General / Header / Footer
    'Pancaran Lelang': 'Pancaran Auctions',
    'Katalog Eksternal': 'External Catalog',
    'Katalog Eksternal (Public)': 'External Catalog (Public)',
    'Area Admin Internal': 'Internal Admin Area',
    'Login Admin': 'Admin Login',
    'Logout Admin': 'Admin Logout',
    'Admin Active': 'Admin Active',
    'Keluar': 'Logout',
    'Pilih Tampilan': 'Select View',
    'Menu Admin': 'Admin Menu',
    'Dashboard Ringkasan': 'Dashboard Summary',
    'Kelola Aset (Tambah & Bids)': 'Manage Assets (Add & Bids)',
    'Manajemen Akses': 'Access Management',
    'Status Koneksi': 'Connection Status',
    'Lelang Aktif': 'Active Auctions',
    'Sedang Berjalan': 'In Progress',
    'Unit Terjual': 'Sold Units',
    'Otorisasi Diperlukan': 'Authorization Required',
    'Halaman internal manajemen Pancaran Lelang dilindungi enkripsi. Silakan masuk menggunakan akun kredensial Anda.': 'The internal management page of Pancaran Lelang is protected by encryption. Please log in using your account credentials.',
    'Masuk Sekarang': 'Log In Now',
    'Hak Cipta Dilindungi': 'All Rights Reserved',
    'Pool Marunda': 'Marunda Pool',
    'Pool Cakung': 'Cakung Pool',
    'Pool Teluk Gong': 'Teluk Gong Pool',
    'Admin Digital Solution': 'Digital Solution Admin',
    'AKUN MASUK:': 'LOGGED IN ACCOUNT:',

    // Catalog View & Cards
    'Cari aset lelang...': 'Search auction assets...',
    'Merek': 'Brand',
    'Kategori': 'Category',
    'Kondisi': 'Condition',
    'Lokasi': 'Location',
    'Semua Merek': 'All Brands',
    'Semua Kategori': 'All Categories',
    'Semua Kondisi': 'All Conditions',
    'Semua Lokasi': 'All Locations',
    'Menampilkan {count} aset yang memenuhi kriteria': 'Showing {count} assets matching criteria',
    'Terbuka': 'Open',
    'Terjual': 'Sold',
    'Th': 'Yr',
    'Harga Pembuka': 'Starting Price',
    'Penawaran Tertinggi': 'Highest Bid',
    'Belum ada penawaran': 'No bids yet',
    'Penawaran': 'Bid(s)',
    'Lihat Detail': 'View Details',
    'Lihat Detail & Ajukan Bid': 'View Details & Submit Bid',
    'Detail Unit Lelang': 'Auction Unit Details',
    'Kembali ke Katalog': 'Back to Catalog',
    'Spesifikasi Unit': 'Unit Specifications',
    'Tahun Pembuatan': 'Year of Manufacture',
    'Nomor Polisi': 'License Plate',
    'Kondisi Fisik': 'Physical Condition',
    'Deskripsi Tambahan': 'Additional Description',
    'Informasi & Tata Cara Lelang': 'Auction Information & Procedure',
    'Aset ini bersifat tangan pertama, memiliki dokumen legalitas (STNK, BPKB, KIR) lengkap dan siap dipindahtangankan setelah pelunasan.': 'This asset is first-hand, has complete legal documents (STNK, BPKB, KIR) and is ready to be transferred after full payment.',
    'Penawaran dilakukan secara terbuka. Setiap penawaran baru wajib lebih tinggi dari penawaran saat ini.': 'Bidding is conducted openly. Each new bid must be higher than the current bid.',
    'Setelah mengajukan penawaran, tim logistik kami akan menghubungi Anda untuk verifikasi dokumen dan penjadwalan inspeksi unit di lokasi pool terkait.': 'After placing a bid, our logistics team will contact you for document verification and scheduling unit inspections at the respective pool location.',
    'Riwayat Penawaran Saat Ini': 'Current Bid History',
    'Nama': 'Name',
    'Nilai Bid': 'Bid Value',
    'Waktu': 'Time',
    'Belum ada penawaran masuk untuk unit ini. Jadilah penawar pertama!': 'No bids received yet for this unit. Be the first bidder!',
    'Formulir Pengajuan Bid Resmi': 'Official Bid Submission Form',
    'Masukkan nama lengkap Anda...': 'Enter your full name...',
    'Contoh: 08123456789': 'Example: 08123456789',
    'Masukkan alamat email aktif...': 'Enter active email address...',
    'Rencana Tanggal Survey': 'Planned Survey Date',
    'Rencana Jam Survey': 'Planned Survey Time',
    'Harga Penawaran Anda (Rupiah)': 'Your Bid Price (Rupiah)',
    'Min. Penawaran Berikutnya:': 'Min. Next Bid:',
    'Kirim Penawaran & Jadwalkan Survey': 'Submit Bid & Schedule Survey',
    'Memproses...': 'Processing...',
    'Silakan isi semua data dengan benar.': 'Please fill all fields correctly.',
    'Penawaran Anda harus lebih besar dari penawaran tertinggi saat ini!': 'Your bid must be higher than the current highest bid!',
    'Penawaran Anda Berhasil Dikirim!': 'Your Bid Successfully Submitted!',
    'Terima kasih telah mengajukan penawaran. Tim Pancaran Logistic akan segera menghubungi Anda di nomor kontak yang tertera.': 'Thank you for submitting a bid. The Pancaran Logistics team will contact you shortly at the provided contact details.',
    'Tutup': 'Close',

    // Login Modal
    'Otoritas Internal Admin': 'Internal Admin Authority',
    'Gunakan email & password terdaftar untuk mengelola sistem lelang.': 'Use registered email & password to manage the auction system.',
    'Email atau password salah. Pastikan kredensial benar.': 'Incorrect email or password. Please ensure credentials are correct.',
    'ALAMAT EMAIL KERJA': 'WORK EMAIL ADDRESS',
    'KATA SANDI (PASSWORD)': 'PASSWORD',
    'Masuk Aplikasi': 'Enter Application',
    'Petunjuk Akun Penguji:': 'Tester Account Tips:',
    'Untuk menguji fitur admin, silakan klik tombol di bawah untuk mengisi kredensial default dari user secara instan.': 'To test admin features, click the button below to instantly fill default credentials.',
    'Isi Kredensial Penguji': 'Fill Tester Credentials',

    // Admin Dashboard
    'Dashboard Utama & Analitik': 'Main Dashboard & Analytics',
    'Ringkasan metrik performa sistem lelang Pancaran Logistics secara real-time.': 'Real-time summary of Pancaran Logistics auction system performance metrics.',
    'Total Asset': 'Total Assets',
    'Unit di Database': 'Units in Database',
    'Sedang Aktif': 'Currently Active',
    'Menerima Penawaran': 'Accepting Bids',
    'Aset Terjual': 'Assets Sold',
    'Sudah Diproses': 'Processed',
    'Total Bidder': 'Total Bidders',
    'Telah Berpartisipasi': 'Have Participated',
    'Aset Terpopuler': 'Most Popular Asset',
    'Dengan Penawaran Terbanyak': 'With Most Bids',
    'Daftar Aktivitas Bid Terbaru': 'Recent Bid Activity List',
    'Aktivitas Terbaru': 'Recent Activity',
    'Daftar pengajuan penawaran harga dari calon pembeli eksternal.': 'List of price bid submissions from external prospective buyers.',
    'Semua Riwayat': 'All History',
    'Aset': 'Asset',
    'Penawar': 'Bidder',
    'Jumlah Penawaran': 'Bid Amount',
    'Tanggal & Waktu': 'Date & Time',
    'Status': 'Status',
    'Tindakan': 'Actions',
    'Belum ada aktivitas penawaran yang terdaftar di sistem.': 'No bid activity registered in the system yet.',
    'Lihat Detail Aset': 'View Asset Details',

    // Admin Assets
    'Daftar Manajemen Aset': 'Asset Management List',
    'Kelola unit logistik yang dilelang, tambahkan unit baru, dan pantau histori penawaran masuk.': 'Manage auctioned logistics units, add new units, and monitor incoming bid history.',
    'Tambah Unit Baru': 'Add New Unit',
    'Semua Aset': 'All Assets',
    'Aktif / Open': 'Active / Open',
    'Terjual / Sold': 'Sold / Closed',
    'Cari aset...': 'Search assets...',
    'Tipe': 'Type',
    'Aksi': 'Actions',
    'Belum ada aset lelang yang cocok dengan pencarian Anda.': 'No auction assets match your search.',
    'PILIH TEMPLATE KENDARAAN (OPSIONAL)': 'SELECT VEHICLE TEMPLATE (OPTIONAL)',
    'Memilih template akan otomatis mengisi Nama, Brand, Kategori, dan gambar ilustrasi standar.': 'Selecting a template will automatically populate Name, Brand, Category, and standard illustration.',
    'FORMULIR MANAJEMEN UNIT ASET': 'UNIT ASSET MANAGEMENT FORM',
    'Nama Kendaraan / Aset': 'Vehicle / Asset Name',
    'Merek / Brand': 'Make / Brand',
    'Kategori Kendaraan': 'Vehicle Category',
    'Tahun': 'Year',
    'Nomor Registrasi (Plat)': 'Registration Number (Plate)',
    'Sangat Baik': 'Excellent',
    'Baik': 'Good',
    'Cukup': 'Fair',
    'Butuh Perbaikan': 'Needs Repair',
    'Lokasi Pool': 'Pool Location',
    'Harga Awal (IDR)': 'Starting Price (IDR)',
    'Deskripsi & Spesifikasi Tambahan': 'Description & Additional Specs',
    'Batal': 'Cancel',
    'Simpan Perubahan': 'Save Changes',
    'Tambah Unit ke Sistem': 'Add Unit to System',
    'Unggah Foto Unit': 'Upload Unit Photo',
    'Klik untuk unggah atau seret foto ke sini': 'Click to upload or drag photo here',
    'Format JPG, PNG maks 5MB. Gambar akan otomatis dikompresi untuk performa optimal.': 'Format JPG, PNG max 5MB. Image will be automatically compressed for optimal performance.',
    'Foto berhasil diunggah': 'Photo successfully uploaded',
    'Hapus Foto': 'Delete Photo',
    'Gambar Utama': 'Primary Image',
    'PILIH ALAT BANTU': 'CHOOSE UTILITIES',
    'Dapatkan Saran Deskripsi dengan AI': 'Get Description Suggestions with AI',
    'Saran Deskripsi': 'Description Suggestions',
    'Gunakan Saran AI': 'Use AI Suggestion',
    'Silakan pilih template atau isi Brand & Kategori terlebih dahulu agar AI dapat menganalisis deskripsi yang relevan.': 'Please select a template or fill in the Brand & Category first so that the AI can analyze relevant descriptions.',
    'Detail Histori Penawaran': 'Bid History Details',
    'Pilih aset di sebelah kiri untuk melihat detail spesifikasi dan histori penawaran secara menyeluruh.': 'Select an asset on the left to view detailed specifications and full bid history.',
    'Detail Spesifikasi': 'Specification Details',
    'Histori Bid': 'Bid History',
    'Ubah Atribut': 'Edit Attributes',
    'Ubah Status': 'Edit Status',
    'Buka Penawaran': 'Open Bidding',
    'Tutup / Selesaikan (Sold)': 'Close / Complete (Sold)',
    'Hapus Unit': 'Delete Unit',
    'Apakah Anda yakin ingin menghapus aset ini secara permanen dari sistem database?': 'Are you sure you want to permanently delete this asset from the database system?',
    'Ya, Hapus': 'Yes, Delete',
    'Tidak': 'No',
    'Rencana Survey:': 'Planned Survey:',
    'Belum ada penawaran untuk unit ini.': 'No bids for this unit.',
    'Bids Masuk': 'Incoming Bids',
    'Hubungi': 'Contact',

    // Admin Users
    'Kelola Hak Akses Admin': 'Manage Admin Privileges',
    'Tambahkan, hapus, dan atur peran pengguna internal yang dapat masuk ke dashboard administrasi.': 'Add, remove, and manage internal users who can access the administration dashboard.',
    'Daftarkan Admin Baru': 'Register New Admin',
    'Nama Lengkap': 'Full Name',
    'Alamat Email Pancaran': 'Pancaran Email Address',
    'Peran / Hak Akses': 'Role / Access Rights',
    'Super Admin': 'Super Admin',
    'Admin Operasional': 'Operational Admin',
    'Admin Keuangan': 'Financial Admin',
    'Daftarkan': 'Register',
    'Akun Terdaftar': 'Registered Accounts',
    'Peran': 'Role',
    'Bergabung': 'Joined',
    'Anda': 'You',
    'Hapus Akses': 'Revoke Access',
    'Apakah Anda yakin ingin menghapus hak akses untuk admin ini?': 'Are you sure you want to revoke access rights for this admin?',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('pancaran_language');
    return (stored === 'en' || stored === 'id') ? (stored as Language) : 'id';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('pancaran_language', lang);
  };

  const t = (key: string, variables?: Record<string, string | number>): string => {
    const translationSet = translations[language];
    let text = translationSet[key] || translations['id'][key] || key;

    if (variables) {
      Object.entries(variables).forEach(([vKey, vVal]) => {
        text = text.replace(`{${vKey}}`, String(vVal));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
